name: diabetes-inference-env
dependencies:
  - python=3.7.2
  - pip3:
    - azureml-defaults
    - scikit-learn==0.21.3
    - numpy
    - inference-schema[numpy-support]
    - pillow==5.4.1
    - conda==4.5.11
      
      
      
