name: diabetes-inference-env
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.7.*
  - pip=20.2.4

  - pip:
    - azureml-defaults
    - azureml-sdk
    - scikit-learn==0.21.3
    - numpy
    - inference-schema[numpy-support]
    - conda=4.12.0
    - pandas      
      
