name: diabetes-training-env
dependencies:
  - python=3.6.2
  - pip:
    - azureml-defaults
    - scikit-learn==0.21.3
    - numpy
    - inference-schema[numpy-support]
    - pillow==5.4.1
    - conda==3.0.6
